name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        scala-version: ["2.12.20","2.13.16","3.3.6"]
        java-version: [ '11', '21' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: guardian/setup-scala@v1
        with:
            major-java-version: ${{ matrix.java-version }}
      - name: lint
        run: >
          sbt ++${{ matrix.scala-version }}
          scalafmtCheck
          test:scalafmtCheck
          scalafmtSbtCheck
      - name: test with coverage
        if: startsWith(matrix.scala-version, '2.12.')
        run: >
          sbt ++${{ matrix.scala-version }}
          coverage
          startDynamodbLocal
          test
          dynamodbLocalTestCleanup
          stopDynamodbLocal
      - name: test without coverage
        if: startsWith(matrix.scala-version, '2.13.') || startsWith(matrix.scala-version, '3.')
        run: >
          sbt ++${{ matrix.scala-version }}
          startDynamodbLocal
          test
          dynamodbLocalTestCleanup
          stopDynamodbLocal
      - name: cleanup
        run: bash <(curl -s https://codecov.io/bash)
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
      - uses: guardian/setup-scala@v1
      - name: test docs
        run: sbt +doc
